### ISSUE TITLE
New updated from vapoursynth

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/AviSynth-VMAF#1]
I seen Vapoursynth updated new ver, please can you port this update to avisynth??

**Comment by Asd-g** [comment]
Those changes currently cannot be simply merged because the recent libvmaf version cannot be build with MSVC. Either the used avisynth cpp api used in the plugin should be changed with avisynth c api or libvmaf should support MSVC again.

**Comment by kedaitinh12** [comment]
Thanks
