### ISSUE TITLE
frame properties output?

### ISSUE THREAD

**Issue by Dogway** [Asd-g/AviSynth-VMAF#2]
I wonder if it would be difficult to output metrics to frame properties for online filtering. For example CAMBI could be fed to GradFun directly.

Thank you!

**Comment by Asd-g** [comment]
There is [such vapoursynth plugin already](https://github.com/AkarinVS/vapoursynth-plugin/blob/master/README.md#cambi). I guess I finally have to compare the speed of it vs vapoursynth-vmaf.

Currently vmaf isn't writing the scores per frame but at once during the closing.

**Comment by Asd-g** [comment]
Please try the attached version.

Usage:
```VMAF2 (clip reference, clip distorted, int[] "model", int[] "feature", string "cambi_opt")```

The parameters are the same as those in README.md.

For example if `VMAF2 (reference, distorted, model=[0,1], feature=[2,5])` is used frame properties with names `model_0`, `model_1`, `feature_2`, `feature_5` will be added to the reference clip.

[VMAF.zip](https://github.com/Asd-g/AviSynth-VMAF/files/8485993/VMAF.zip)

**Comment by Dogway** [comment]
Thanks a lot!
I could test it and got issues with feature=0 and 4 (error requesting frame #) and feature=1 (nan).
I also get locked scores of 100.00 for model=[0,1,2,3], unless I do some extreme changes (like shifting the image).

I compared this with VMAF 2.1.0 and for the given frame 239 it scored 88.57.
```
Frame,integer_motion2,integer_motion,integer_adm2,integer_adm_scale0,integer_adm_scale1,integer_adm_scale2,integer_adm_scale3,integer_vif_scale0,integer_vif_scale1,integer_vif_scale2,integer_vif_scale3,vmaf,
239,2.632987,2.632987,0.943636,0.929544,0.886560,0.948309,0.977007,0.360506,0.986009,0.994040,0.996246,88.570110,
```

My call:
```
ConvertBits(16)
ref=last
distorted=ex_MinBlur(2)
VMAF2(ref, distorted, model=[0,1,2,3])
propshow()
```

**Comment by Asd-g** [comment]
Removed parameter `model` and `feature=1` is not allowed because these scores are result from few frames (> 4).
The names of the frame properties are renamed to the same one in the log from `VMAF()`.
The original `VMAF()` function is also included.

Usage:
`VMAF (clip reference, clip distorted, string log_path, int "log_format", int[] "model", int[] "feature", string "cambi_opt")`
`VMAF2 (clip reference, clip distorted, int[] "feature", string "cambi_opt")`

[VMAF.zip](https://github.com/Asd-g/AviSynth-VMAF/files/8499241/VMAF.zip)

**Comment by Dogway** [comment]
Thanks! Working great now. 5 (CAMBI) gave me a crash but I need to read more on 'cambi_opt' arg and play with it.
`VMAF2(ref, distorted, feature=[0,2,3,4])`

If I understand it correctly, VMAF and PSNR-HVS require acummulated stats?
Closing, thanks for looking into it.

**Comment by Asd-g** [comment]
There will be a crash if `feature=5` is used together with some of the other features.

Yes, both VMAF and PSNR-HVS require acummulated stats. If you try the first test version using model=x, the frame property on the first frame of the clip should give the same score as the one in the log.
